<?php
$pageTitle = 'Projects';
$activePage = 'projects';
require_once __DIR__ . '/../includes/header.php';
require_permission('manage_projects');
$projects = $pdo->query("SELECT p.*, c.company, u.name manager FROM projects p JOIN clients c ON c.id = p.client_id LEFT JOIN users u ON u.id = p.manager_id ORDER BY p.due_date")->fetchAll();
?>
<div class="d-flex justify-content-between align-items-end mb-4"><div><span class="section-kicker">Delivery portfolio</span><h2 class="mt-2">Projects</h2><p class="text-muted mb-0">The workbench for every client engagement.</p></div><a href="<?= url('projects/create.php') ?>" class="btn btn-primary"><i class="bi bi-plus-lg me-2"></i>New project</a></div>
<div class="table-shell"><div class="table-responsive"><table class="table"><thead><tr><th>Project</th><th>Client</th><th>Manager</th><th>Deadline</th><th>Budget</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($projects as $project): ?><tr><td><span class="table-title"><?= e($project['name']) ?></span><span class="table-subtitle"><?= e($project['technologies']) ?></span></td><td><?= e($project['company']) ?></td><td><?= e($project['manager'] ?? 'Unassigned') ?></td><td><?= e(date('M d, Y', strtotime($project['due_date']))) ?></td><td><?= e(money($project['budget'])) ?></td><td><span class="status-badge status-<?= strtolower(str_replace(' ', '-', $project['status'])) ?>"><?= e($project['status']) ?></span></td><td><div class="d-flex align-items-center gap-2"><a class="text-link" href="<?= url('projects/view.php?id=' . $project['id']) ?>">Open</a><a class="icon-button" href="<?= url('projects/edit.php?id=' . $project['id']) ?>" title="Edit project"><i class="bi bi-pencil"></i></a><form method="post" action="<?= url('projects/delete.php?id=' . $project['id']) ?>" data-confirm="Delete this project and all linked tasks and milestones? This cannot be undone."><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><button class="icon-button text-danger" type="submit" title="Delete project"><i class="bi bi-trash"></i></button></form></div></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
