<?php
$pageTitle = 'Project workspace';
$activePage = 'projects';
require_once __DIR__ . '/../includes/header.php';
require_permission('manage_projects');
$id = (int) ($_GET['id'] ?? 0);
$statement = $pdo->prepare('SELECT p.*, c.company, c.email client_email, u.name manager FROM projects p JOIN clients c ON c.id = p.client_id LEFT JOIN users u ON u.id = p.manager_id WHERE p.id = ?');
$statement->execute([$id]);
$project = $statement->fetch();
if (!$project) { http_response_code(404); exit('Project not found.'); }
$tasksStatement = $pdo->prepare('SELECT * FROM tasks WHERE project_id = ? ORDER BY due_date');
$tasksStatement->execute([$id]);
$tasks = $tasksStatement->fetchAll();
$milestonesStatement = $pdo->prepare('SELECT * FROM milestones WHERE project_id = ? ORDER BY due_date');
$milestonesStatement->execute([$id]);
$milestones = $milestonesStatement->fetchAll();
?>
<div class="d-flex justify-content-between align-items-end mb-4"><div><span class="section-kicker"><?= e($project['company']) ?> / Workspace</span><h2 class="mt-2"><?= e($project['name']) ?></h2><p class="text-muted mb-0"><?= e($project['description']) ?></p></div><div class="d-flex gap-2 align-items-center"><span class="status-badge status-<?= strtolower(str_replace(' ', '-', $project['status'])) ?>"><?= e($project['status']) ?></span><a class="icon-button" href="<?= url('projects/edit.php?id=' . $id) ?>" title="Edit project"><i class="bi bi-pencil"></i></a><form method="post" action="<?= url('projects/delete.php?id=' . $id) ?>" data-confirm="Delete this project and all linked tasks and milestones? This cannot be undone."><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><button class="icon-button text-danger" type="submit" title="Delete project"><i class="bi bi-trash"></i></button></form></div></div>
<div class="stats-grid"><article class="stat-card tone-blue"><div class="stat-top"><span>Budget</span><i class="bi bi-wallet2"></i></div><strong><?= e(money($project['budget'])) ?></strong><small><?= e($project['priority']) ?> priority</small></article><article class="stat-card tone-green"><div class="stat-top"><span>Health score</span><i class="bi bi-heart-pulse"></i></div><strong>87%</strong><small>On track this week</small></article><article class="stat-card tone-amber"><div class="stat-top"><span>Deadline</span><i class="bi bi-calendar3"></i></div><strong><?= e(date('M d', strtotime($project['due_date']))) ?></strong><small><?= e($project['manager'] ?? 'Unassigned') ?></small></article><article class="stat-card tone-blue"><div class="stat-top"><span>Technology</span><i class="bi bi-code-slash"></i></div><strong><?= e((string) count(explode(',', (string) $project['technologies']))) ?></strong><small><?= e($project['technologies']) ?></small></article></div>
<div class="dashboard-grid"><section class="panel"><div class="panel-heading"><div><span class="section-kicker">Delivery</span><h3>Milestones</h3></div><a href="<?= url('tasks/create.php') ?>" class="text-link">Add task <i class="bi bi-plus"></i></a></div><?php foreach ($milestones as $milestone): ?><div class="health-row"><span><?= e($milestone['name']) ?></span><strong><?= e((string) $milestone['progress']) ?>%</strong><div class="progress"><div class="progress-bar" style="width:<?= e((string) $milestone['progress']) ?>%"></div></div></div><?php endforeach; ?></section><section class="panel"><div class="panel-heading"><div><span class="section-kicker">Client</span><h3><?= e($project['company']) ?></h3></div><i class="bi bi-building text-primary"></i></div><p class="mb-1"><?= e($project['client_email']) ?></p><hr><p class="small text-muted mb-1">Repository</p><a class="text-link" href="<?= e($project['repository_url'] ?: '#') ?>"><?= e($project['repository_url'] ?: 'Not connected') ?></a></section></div>
<section class="panel"><div class="panel-heading"><div><span class="section-kicker">Execution</span><h3>Project tasks</h3></div><a href="<?= url('tasks/') ?>" class="text-link">All tasks <i class="bi bi-arrow-up-right"></i></a></div><div class="table-responsive"><table class="table"><thead><tr><th>Task</th><th>Priority</th><th>Due</th><th>Status</th></tr></thead><tbody><?php foreach ($tasks as $task): ?><tr><td class="table-title"><?= e($task['title']) ?></td><td><?= e($task['priority']) ?></td><td><?= e(date('M d, Y', strtotime($task['due_date']))) ?></td><td><span class="status-badge status-<?= strtolower(str_replace(' ', '-', $task['status'])) ?>"><?= e($task['status']) ?></span></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
