<?php
declare(strict_types=1);
$pageTitle = 'Clients';
$activePage = 'clients';
require_once __DIR__ . '/../includes/header.php';
require_permission('manage_clients');
$clients = $pdo->query("SELECT c.*, COUNT(p.id) project_count, COALESCE(SUM(p.budget), 0) project_value FROM clients c LEFT JOIN projects p ON p.client_id = c.id GROUP BY c.id ORDER BY c.created_at DESC")->fetchAll();
?>
<div class="d-flex justify-content-between align-items-end mb-4"><div><span class="section-kicker">Relationships</span><h2 class="mt-2">Client directory</h2><p class="text-muted mb-0">Keep every account, project, and conversation in view.</p></div><a href="<?= url('clients/create.php') ?>" class="btn btn-primary"><i class="bi bi-plus-lg me-2"></i>Add client</a></div>
<div class="table-shell"><div class="p-3 border-bottom"><div class="search-box w-100"><i class="bi bi-search"></i><input type="search" placeholder="Filter clients"></div></div><div class="table-responsive"><table class="table"><thead><tr><th>Client</th><th>Contact</th><th>Projects</th><th>Portfolio value</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($clients as $client): ?><tr><td><span class="project-icon d-inline-grid me-2"><?= e(strtoupper(substr($client['company'], 0, 1))) ?></span><span class="table-title"><?= e($client['company']) ?></span><span class="table-subtitle ms-5"><?= e($client['name']) ?></span></td><td><?= e($client['email']) ?><span class="table-subtitle"><?= e($client['phone']) ?></span></td><td><?= e((string) $client['project_count']) ?> active</td><td><?= e(money($client['project_value'])) ?></td><td><span class="status-badge status-<?= $client['status'] === 'active' ? 'healthy' : 'not-started' ?>"><?= e(ucfirst($client['status'])) ?></span></td><td><div class="d-flex align-items-center gap-2"><a class="text-link" href="<?= url('clients/view.php?id=' . $client['id']) ?>">Open</a><a class="icon-button" href="<?= url('clients/edit.php?id=' . $client['id']) ?>" title="Edit client"><i class="bi bi-pencil"></i></a><form method="post" action="<?= url('clients/delete.php?id=' . $client['id']) ?>" data-confirm="Delete this client and all linked projects, tasks, and milestones? This cannot be undone."><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><button class="icon-button text-danger" type="submit" title="Delete client"><i class="bi bi-trash"></i></button></form></div></td></tr><?php endforeach; ?></tbody></table></div></div>
+<?php require_once __DIR__ . '/../includes/footer.php'; ?>
