<?php
$pageTitle = $pageTitle ?? 'Dashboard';
$activePage = $activePage ?? 'dashboard';
require_once __DIR__ . '/auth-check.php';
$flashMessages = pull_flash();
$notificationCount = (int) $pdo->query("SELECT COUNT(*) FROM tasks WHERE status <> 'Done' AND due_date <= DATE_ADD(CURDATE(), INTERVAL 7 DAY) AND due_date IS NOT NULL")
	->fetchColumn();
$notificationCount += (int) $pdo->query("SELECT COUNT(*) FROM projects WHERE status NOT IN ('Completed', 'Cancelled') AND due_date <= DATE_ADD(CURDATE(), INTERVAL 30 DAY) AND due_date IS NOT NULL")
	->fetchColumn();
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= e($pageTitle) ?> | BENEST</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"><link href="<?= url('assets/css/app.css') ?>" rel="stylesheet"><link href="<?= url('assets/css/dark-mode.css') ?>" rel="stylesheet"></head><body>
<div class="app-shell"><aside class="sidebar" id="sidebar"><?php require __DIR__ . '/sidebar.php'; ?></aside><main class="main-content"><header class="topbar"><button class="icon-button mobile-toggle" data-sidebar-toggle aria-label="Open navigation"><i class="bi bi-list"></i></button><div><p class="eyebrow mb-1">Workspace / <?= e($pageTitle) ?></p><h1 class="page-title mb-0"><?= e($pageTitle) ?></h1></div><div class="topbar-actions"><button class="icon-button theme-toggle" data-theme-toggle type="button" title="Toggle dark mode" aria-label="Toggle dark mode"><i class="bi bi-moon-stars"></i><span>Dark</span></button><div class="search-box"><i class="bi bi-search"></i><input id="globalSearch" type="search" placeholder="Search anything"></div><a class="icon-button position-relative" href="<?= url('notifications/') ?>" title="Notifications" aria-label="Notifications"><i class="bi bi-bell"></i><?php if ($notificationCount > 0): ?><span class="notification-count"><?= e((string) min($notificationCount, 99)) ?></span><?php endif; ?></a><div class="dropdown"><button class="profile-chip dropdown-toggle" data-bs-toggle="dropdown"><span class="avatar"><?= e(strtoupper(substr(current_user()['name'], 0, 1))) ?></span><span class="d-none d-md-inline"><?= e(current_user()['name']) ?></span></button><ul class="dropdown-menu dropdown-menu-end"><li><span class="dropdown-item-text small text-muted"><?= e(current_user()['role']) ?></span></li><li><a class="dropdown-item" href="<?= url('settings/') ?>">Account settings</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item text-danger" href="<?= url('auth/logout.php') ?>">Log out</a></li></ul></div></div></header><?php foreach ($flashMessages as $message): ?><div class="alert alert-<?= e($message['type']) ?> alert-dismissible fade show mt-3" role="alert"><?= e($message['message']) ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div><?php endforeach; ?><div class="page-body">
